naiveBayes:
	javac NaiveBayes.java
	javac CreaMatriz.java
	javac NBAdultDataSet.java
	java NBAdultDataSet
testNaiveBayes:
	javac NaiveBayes.java
	javac CreaMatriz.java
	javac TestAdultDataSet.java
	java TestAdultDataSet